---
title: "PubTree - Explore scientific publications and their relationships"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      bootswatch: sandstone
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# orientation: rows
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(igraph)
library(ggraph)
library(xml2)
library(mclust)
source("functions.R")
```

```{r, include=F}
library(GAlogger)
ga_set_tracking_id(as.character(read.table("bigBrother.txt", header = F)))
ga_collect_pageview(page = "/start")
ga_set_approval(consent = TRUE)
```

Search {.sidebar}
-----------------------------------------------------------------------

Current article

```{r}
textOutput("currentTitle")
```

<hr>

```{r}
textInput("PMID", label = "Enter PMID", value = "30426166")
actionButton("go", "Retrieve publication")

data <- reactiveValues()

observeEvent(input$go, {
  
  ga_collect_event(event_category = "Start", event_action = "Searching PMID")
  
  if(is.null(data$i)){
    data$i <- 1
    data$data <- NULL
  }else{
    data$i <- 1 + data$i
  }
  
  data$data[[data$i]] <- getInfo(id = input$PMID) |> 
    withProgress(message = "Downloading information", 
                 value = .5) |> 
    try()
  
  if(class(data$data[[data$i]]) == "try-error"){
    
    ga_collect_event(event_category = "Start", event_action = "Error in getInfo")
    
    showNotification("Something went wrong, try again or try different article")
    output$plot <- renderPlot(
          ggplot() +
            geom_text(aes(label="Something went wrong.\nTry again or try different PMID", 
                          x = 1, y = 1)) +
            theme_void())
    
    if(length(data$data)>1){
      if(data$i == 1){
        data$data[[data$i]] <- NULL
      }else{
        data$data[[data$i]] <- NULL
        data$i <- data$i - 1
      }
    }else{
      data$data <- NULL
      data$i <- data$i - 1
    }
    
  }
})
```

<hr>

Previous articles

```{r}
actionButton("back", 
             label = HTML("<span class='small'><i class='glyphicon glyphicon-arrow-left'></i> Back</span>"))
actionButton("delete", 
             label = HTML("<span class='small'></span><i class='glyphicon glyphicon-trash'></i>"))
actionButton("forward", 
             label = HTML("<span class='small'>Forward </span><i class='glyphicon glyphicon-arrow-right'></i>"))


observeEvent(input$back,{
  ga_collect_event(event_category = "Nav", event_action = "Navigating back and forth")
  
  req(data$i)
  if(data$i>1){
    data$i <- data$i - 1
  }
})
observeEvent(input$delete,{
  ga_collect_event(event_category = "Nav", event_action = "Deleting")
  
  req(data$i)
  if(length(data$data)>1){
    if(data$i == 1){
      print(data$i)
      data$data[[data$i]] <- NULL
    }else{
      data$data[[data$i]] <- NULL
      data$i <- data$i - 1
    }
  }
})
observeEvent(input$forward, {
  ga_collect_event(event_category = "Nav", event_action = "Navigating back and forth")

  req(data$i)
  if (data$i < length(data$data)) {
    data$i <- data$i + 1
  }
})
```

```{r}
tableOutput("table")

output$table <- renderTable({
  req(data$data)
  listArticles <- sapply(data$data, \(x) x$meta$title[x$meta$order == "root"])
  listArticles <- data.frame(order = 1:length(listArticles), 
                             title = stringr:: str_trunc(listArticles, 20, "right"))
  colnames(listArticles) <- NULL
  if(nrow(listArticles)>5){
    return(listArticles[(nrow(listArticles) - 5):nrow(listArticles)])
  }else{
      return(listArticles)
  }
})
```

```{r}
downloadLink("downloadData", "Download articles")
```

```{r}
output$downloadData <- downloadHandler(
  filename = function() {
    req(data$data)
    paste0(Sys.Date(), ".xlsx", sep = "")
  },
  content = function(file) {
    x <- lapply(data$data, \(x) x$meta[x$meta$order == "root",])
    x <- Reduce(rbind, x)
    x[is.na(x)] <- "Not available"
    x$FulltextUrl <- paste0("https://pubmed.ncbi.nlm.nih.gov/", x$PMID)
    
    openxlsx::write.xlsx(x = x, file = file)
  }
)
```

<hr>

```{r, height = 50}
sliderInput(
  "size",
  "Node size",
  min = 0.5,
  max = 4,
  step = .2,
  value = 2
)
```

<hr>

```{r}
radioButtons(inputId = "summarize", 
             label = "View", 
             choices = c("Focus", "Overview"), 
             selected = "Focus", 
             width = "20%")
```

<hr>

```{r}
selectizeInput(inputId = "mesh",
               label =  "Filter articles by MESH terms", 
               choices = NULL,
               selected = NULL, 
               multiple = T)
actionButton(inputId = "filter", "Filter")
actionButton(inputId = "clear", "Clear")
```

<hr>

***Disclaimer*** these results do not represent all scientific articles. They only include articles that are freely availble on PubMed and which have a Pubmed ID (PMID). There is also a 200 article limit on the number of articles presented. 

**Data sources:** Pubmed central API

**Author:** Leonidas Lundell PhD

**Email:** leonidas.lundell@gmail.com

Column {data-width=1000, data-height=1000}
-----------------------------------------------------------------------

```{r}
#instructions
output$plot <- renderPlot(
      ggplot() + 
        geom_text(aes(label="Start with an intresting article.\nExplore its context.", 
                      x = 1, y = 0), size = 12) + 
        theme_void())
```

### Pubmed citation network

```{r}
#zoom
observeEvent(input$zoomClick, {
  req(data$i)
  brush <- input$zoomRange
  if (!is.null(brush)) {
    ga_collect_event(event_category = "View", event_action = "Zoom in")
    
    ranges$x <- c(brush$xmin, brush$xmax)
    ranges$y <- c(brush$ymin, brush$ymax)
    
  } else {
    ga_collect_event(event_category = "View", event_action = "Zoom out")
    
    ranges$x <- NULL
    ranges$y <- NULL
  }
})
```


```{r, }
observeEvent(
  input$go |
    input$forward |
    input$back |
    input$delete | 
    input$filter |
    input$clear |
    as.numeric(as.factor(input$summarize)),
  {
    #
  Sys.sleep(.1)
  req(data$i)
  req(data$data[[data$i]])
  
  #update the presented mesh terms
  meshTerms <- unlist(data$data[[data$i]]$meta$meshTerms, use.names = F)
  meshID <- unlist(sapply(data$data[[data$i]]$meta$meshTerms, names), 
                      use.names = F)
  #different descriptions for the same mesh id
  meshTerms <- meshTerms[!duplicated(meshID)]
  meshID <- meshID[!duplicated(meshID)]
  names(meshID) <- meshTerms
  
  updateSelectizeInput(inputId = "mesh",
                       choices = sort(meshTerms))
  
  mesh2article <- sapply(data$data[[data$i]]$meta$meshTerms, names)
  keep <- meshID[input$mesh]
  keep <- sapply(mesh2article, \(x) any(x %in% keep))
  keep[[data$data[[data$i]]$meta[data$data[[data$i]]$meta$order == "root", "PMID"]]] <- TRUE #keep the root
  
  #title
  output$currentTitle <- renderText(data$data[[data$i]]$meta[data$data[[data$i]]$meta$order == "root",
                                                             "title"])
  
  #check if the view is summarized or not
  if(input$summarize == "Overview"){
    ga_collect_event(event_category = "View", 
                     event_action = "Viewed in Overview mode")
    
    data$gg <- net(results = data$data, layout = "other") |> 
      withProgress(message = "Clustering articles", 
                   value = .5)
    
    output$plot <- renderPlot({
      gg <- plotNet(
        ggDat = data$gg,
        maxSize = max(data$data[[data$i]]$meta$citations),
        nodeSize = input$size,
        y = ranges$x,
        x = ranges$y
      )
      return(gg)
    })
  }else{
    ga_collect_event(event_category = "View", 
                     event_action = "Viewed in Standard mode")
    
    if(is.null(input$mesh)){
      g <- data$data[[data$i]]
    }else{
      g <- lapply(data$data[[data$i]], \(x){
        x[keep, ]
      })
    }
    
    data$gg <- net(results = g) |> withProgress(message = "Clustering articles",
                                                value = .5)
    
    output$plot <- renderPlot({
      gg <- plotNet(
        data$gg,
        maxSize = max(data$data[[data$i]]$meta$citations),
        nodeSize = input$size,
        y = ranges$x,
        x = ranges$y
      )
      return(gg)
    })
  }
  
})

ranges <- reactiveValues(x = NULL, y = NULL)

plotOutput("plot", 
           click = "plotClick",
           dblclick = "zoomClick",
           brush = brushOpts(
             id = "zoomRange",
             resetOnNew = TRUE
           ))
```

```{r}
# observeEvent(input$mesh,{
#   Sys.sleep(1)
#   if(!is.null(input$mesh)){
#     keep <- data$meshTerms[input$mesh]
#     data$keep <- data$data[[data$i]]
#     
#     mesh2article <- sapply(data$data[[data$i]]$meta$meshTerms, names)
#     keep <- sapply(mesh2article, \(x) any(x %in% keep))
#     keep[data$keep$meta[data$keep$meta$order == "root","PMID"]] <- TRUE
#     
#     data$data[[data$i]]$df <- data$data[[data$i]]$df[keep,]
#     data$data[[data$i]]$meta <- data$data[[data$i]]$meta[keep,]
#   }else{
#     if(!is.null(data$keep)){
#       data$data[[data$i]] <- data$keep
#       data$keep <- NULL 
#     }
#   }
#   
# })
```


Column  {data-width=1000}
-----------------------------------------------------------------------

```{r}
observeEvent(input$plotClick,{
  req(data$i)
  ga_collect_event(event_category = "View", event_action = "Clicked on node")
  
  data$article <- nearPoints(data$gg,
                             input$plotClick,
                             maxpoints = 1, 
                             threshold = 40)
  
  if(nrow(data$article) == 0){
    PMID <- data$data[[data$i]]$meta[data$data[[data$i]]$meta$order == "root", "PMID"]
    data$article <- data$gg[data$gg$name == PMID, ]
  }
  
  updateTextInput(session, "PMID", value = data$article$name)
  
  tbl <- data.frame(Title = stringr::str_trunc(data$article$title, 200, "right"),
                    Journal = data$article$journal,
                    Type = data$article$type,
                    Authors = data$article$author,
                    Year = data$article$year,
                    Language = data$article$language,
                    Citations = round(data$article$citations - 0.2, digits = 0)
  )
  colnames(tbl)[2] <- "Journal"#some returns make the colname null?
  
  output$header <- renderTable(tbl)
  output$abstract <- renderText(data$article$abstract)
})
```

### 

```{r,fig.height=30}
fluidPage(tableOutput("header"))
```

<br>

```{r}
observeEvent(input$plotClick,{
  req(data$i)
  output$link <- renderUI(tags$a(href = paste0("https://pubmed.ncbi.nlm.nih.gov/", input$PMID),
                                 target="_blank", 
                                 "Full text article"))
})

uiOutput("link")
```

### Abstract

```{r,fig.height=70}
textOutput("abstract")
# span(textOutput("abstract"), style="color:red")
```

